# Run `workflow-pathoscope` alongside Mongo and Redis.
version: "3.8"
services:
  pathoscope:
    build: .
    image: workflow-pathoscope
    environment:
      - VT_DB_CONNECTION_STRING=mongodb://mongo:27017
      - VT_REDIS_CONNECTION_STRING=redis://redis:6379
    command: "1"

  mongo:
    image: mongo:4.4
    logging:
      driver: none

  redis:
    image: redis:6.0
    logging:
      driver: none

